name: project-check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: clone repository
        uses: actions/checkout@v4
      - name: npm chaching
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install packages
        run: make install
      - name: run snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: build project
        run: make build
      - name: linting typescript
        run: make lint
      - name: testing
        run: make test